apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: ghcr.io/kubeflow/dashboard/poddefaults-webhook
        name: poddefaults-webhook
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-cert
          readOnly: true
        ports:
        - name: https-webhook
          containerPort: 4443
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      volumes:
      - name: webhook-cert
        secret:
          secretName: poddefaults-webhook-certs
      serviceAccountName: service-account
