version: 2
updates:

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"

  # Disabled until we're in a state where we can actually take care of the
  # updates proposed by dependabot
  #
  # - package-ecosystem: "gomod"
  #   open-pull-requests-limit: 5
  #   cooldown:
  #     default-days: 7
  #   directories:
  #     - "/components/access-management"
  #     - "/components/poddefaults-webhooks"
  #     - "/components/profile-controller"
  #   schedule:
  #     interval: "daily"
  #   commit-message:
  #     prefix: "chore"
