apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: SERVICE_MESH_MODE
          value: istio-ambient
        - name: WAYPOINT_NAME
          value: waypoint
        - name: WAYPOINT_NAMESPACE
          value: ""
        - name: CREATE_WAYPOINT
          value: "true"