apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: SERVICE_MESH_MODE
          value: istio-ambient