name: CentralDashboard Frontend Tests
on:
  pull_request:
    paths:
      - components/centraldashboard/**
      - releasing/version/VERSION
    branches:
      - main
      - v*-branch

jobs:
  frontend-tests:
    runs-on: ubuntu-22.04
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node version to 16.20.2
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run frontend tests
        run: |
          cd components/centraldashboard
          npm install
          CHROMIUM_BIN=$(which chrome) npm run test
