name: Run the Access Management unit tests
on:
  pull_request:
    paths:
      - components/access-management/**
      ## NOTE: we also test on changes to profile-controller as access-management depends on profile-controller
      - components/profile-controller/**
      - releasing/version/VERSION
    branches:
      - main
      - v*-branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: components/access-management/go.mod
        check-latest: true
        cache-dependency-path: components/access-management/go.sum

    - name: Run unit tests
      run: |
        cd components/access-management
        make test

    - name: Check if there are uncommitted file changes
      working-directory: components/access-management
      run: |
        clean=$(git status --porcelain)
        if [[ -z "$clean" ]]; then
            echo "Empty git status --porcelain: $clean"
        else
            echo "Uncommitted file changes detected: $clean"
            git diff
            exit 1
        fi
