name: Build & Publish Profile Controller OCI image
on:
  push:
    branches:
      - main
      - v*-branch
    paths:
      - components/profile-controller/**
      - releasing/version/VERSION

env:
  IMG: ghcr.io/kubeflow/dashboard/profile-controller
  ARCH: linux/amd64,linux/ppc64le,linux/arm64/v8

permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Build & Push OCI image to GHCR
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            version:
              - 'releasing/version/VERSION'

      - name: Login to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Build and push multi-architecture OCI image (commit tag)
        run: |
          cd components/profile-controller
          make docker-build-multi-arch
          make docker-build-push-multi-arch

      - name: Build and push multi-architecture OCI image (latest tag)
        if: github.ref == 'refs/heads/main'
        run: |
          export TAG=latest
          cd components/profile-controller
          make docker-build-push-multi-arch

      - name: Build and push multi-architecture OCI image (version tag)
        id: version
        if: steps.filter.outputs.version == 'true'
        run: |
          export TAG=$(cat releasing/version/VERSION)
          cd components/profile-controller
          make docker-build-push-multi-arch
