name: Profile Controller Multi-Arch Build Test
on:
  pull_request:
    paths:
      - components/profile-controller/**
      - releasing/version/VERSION
    branches:
      - main
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  IMG: ghcr.io/kubeflow/dashboard/profile-controller
  ARCH: linux/amd64,linux/ppc64le,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build multi-arch Image
      run: |
        cd components/profile-controller
        make docker-build-multi-arch
